@startuml
entity User
entity "journal.csv" as CSVFile {
  _entry: "csv"
  _prompt: csv
  _date: csv
}

class Program {
  +menuOptions: list
    1. readEntries
    2. writeEntries
    3. setFilePath
    4. quit
  +switch(menuOption: int)
}

class Journal {
  _filePath: string
  _entry: string
  _currentDate: string
  _prompt: string
  +SetFilePath(_filePath: string)
  +DisplayJournal()
  +WriteJournal()
}

class Prompts {
  +promptList: list
  +Prompt()
}

User -> Program: Runs Program
Program --> User: Returns Results

Program -> Journal: Read Journal Entries
Program -> Journal: Writes Journal Entries
Program -> Journal: Change Filepath
Journal --> Program: Returns Entries

Journal -> Prompts: Requests Journal Prompts
Prompts --> Journal: Returns Prompt

Journal -> CSVFile: Save New Entries
CSVFile --> Journal: Load Entries

CSVFile -[hidden]-> Prompts
@enduml